name: Build

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Run npm install
      run:  npm install

    - name: Run lint
      run: npm run lint
